name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        nvim_version: [nightly, stable]
    env:
      NVIM_RELEASE_URL: https://github.com/neovim/neovim/releases/download/${{ matrix.nvim_version }}/nvim-linux64.tar.gz
    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Restore from todays cache
        uses: actions/cache@v4
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.nvim_version }}-${{ hashFiles('todays-date') }}

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y fd-find mlocate

          test -d _neovim || {
            mkdir -p _neovim
            echo "Downloading $NVIM_RELEASE_URL..."
            curl -sL $NVIM_RELEASE_URL | tar -zxf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Download plugins
        run: |
          NVIM_PLUGIN_PATH=~/.local/share/nvim/site/pack/vendor/start
          mkdir -p $NVIM_PLUGIN_PATH
          ln -s ${PWD} $NVIM_PLUGIN_PATH

          cd $NVIM_PLUGIN_PATH
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:$PATH"
          nvim --version
          make test

  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: make lint

  check_style:
    name: check style
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # CLI arguments
          args: --color always --check lua/
